---
title: "Compare our results with other trait databases"
author: "TP DuBose"
date: "06/08/2022"
output: pdf_document
---

```{r setup, include=F}
library(tidyverse); library(knitr)
```

```{r}
trait_long<-read_csv('../ATraiU2_full_2022MAY_2.csv', show_col_types = F) %>%
  filter(!(traitName %in% c("Water Loss Rate",
                        "Minimum Egg Development Temperature",
                        "Maximum Egg Development Temperature",
                        "Metabolic Rate", "Metabolism Rate",
                        'Tforage_optim'))) %>%
  distinct(traitName, species, refID, traitValue, .keep_all=T) 
refs <- read_csv('../ATraiU2_reference_list_2022MAY.csv', show_col_types = F) %>%
  select(-`...1`)
taxa_key<-read.csv('../ATraiU2_taxonomic_key_2022MAY.csv')
foc_taxa<-gsub(' MNM traits','', sp_files$name)
```
# GlobTherm comparison ----

```{r}
trait_long %>% filter(traitName %in% c('CTmax', 'CTmin'),
                      species %in% foc_taxa,
                      lifeStage %in% c('adult','unknown')) %>%
  distinct(species, traitName, refID) %>%
  pivot_wider(names_from=traitName, values_from=refID, 
              values_fn=function(x){paste(x, collapse=',')})
globaltherm<-read.csv('C:/Users/Owner/Downloads/GlobTherm/GlobalTherm_upload_02_11_17.csv')
gt_anurans<-globaltherm %>% filter(Order=='Anura') %>%
  mutate(species1=paste(Genus, Species)) %>%
  filter(species1 %in% c(trait_long$species, trait_long$canonicalName)|
           Genus %in% c(unique(trait_long$genus), 'Hyla', 'Bufo'))

gt_anurans %>% select(Genus, Species, N, Tmax, tmin, REF_max, REF_min) %>% View()
refs %>% filter(grepl('Brattstrom', first_author)) %>%
  select(Source.file.name, refID, first_author)
refs %>% filter(grepl('Mahoney', first_author)) %>%
  select(Source.file.name, refID, first_author)
refs %>% filter(grepl('Holzma', first_author)) %>%
  select(Source.file.name, refID, first_author)
```

So with that sheet, I can compare it with the trait_long table to see if we got everything. I typically do it by reference. 

```{r}
# references missed
# Brattstrom 1970 --- Austrailian frogs, not in scope
# Christian_et_al_1988 --- E. coqui (not searched for)
# MacArthur_&_Dandy_1982 - should have picked up
library(readxl)
globaltherm_ref<-readxl::read_xlsx('C:/Users/Owner/Downloads/GlobTherm/References_1_09_2017.xlsx')

globaltherm_ref %>% filter(grepl('Christian_et_al_1988', `Data citation`) | 
                             grepl('MacArthur_&_', `Data citation`)|
                           grepl('Brattstrom_1970', `Data citation`)|
                             grepl('Holzman_', `Data citation`)) %>% 
  pull(Reference)

trait_db_raw %>%
  filter(traitName %in% c('CTmax', 'CTmin') & `Life Stage`=='adult',
         !(`Source file name` %in% c('Brattstrom 1968', 'Layne1985_CTmin',
                                     'Miller & Packard 1977'))) %>%
  View()
```
# AmphiBIO comparison ---- 

```{r}
amphibio<-read.csv('C:/Users/Owner/Downloads/AmphiBIO_v1/AmphiBIO_v1.csv')
amphi_foc<-amphibio %>% filter(Species %in% foc_taxa) %>% 
  select(Genus, Species, Diu, Noc, Crepu, Body_mass_g) 
atraiu2_has<-trait_long %>% filter(species %in% foc_taxa,
                      lifeStage %in% c('adult', 'unknown'),
                      traitName %in% c('Activity', 'Mass')) %>%
  distinct(species, traitName, refID) %>%
  pivot_wider(names_from=traitName, values_from=refID, 
              values_fn=function(x){paste(x, collapse=',')}) %>%
  arrange(species)
amphi_foc %>% filter(is.na(Body_mass_g)) %>%
  left_join(atraiu2_has, by=c('Species'='species')) %>%
  filter(!is.na(Mass))

amphi_foc %>% filter(is.na(Diu)&is.na(Noc)&is.na(Crepu)) %>%
  left_join(atraiu2_has, by=c('Species'='species')) %>%
  filter(!is.na(Activity))
```

```{r}

```

```{r, eval=F}
amphibioCOMP<-amphibio %>% filter(Order =='Anura') %>% 
  # select only columns shared between datasets
  dplyr::select(Family, Genus, Species, Noc, Diu, Crepu, Body_mass_g, OBS) %>% 
  # join the taxa key to make species align
  right_join(taxa_key, by=c("Species"="species"))%>%
  filter(Species %in% foc_taxa,
         !is.na(Genus)) %>%
  # join with our trait database
  right_join(trait_long %>% 
               # isolate columns we need & pivot to wide DB
              filter(traitName %in% c('Activity','Mass'), 
                     lifeStage %in% c('adult','unknown')) %>%
              select(species, traitName, traitValue) %>%
              group_by(species) %>% 
               # each row will be a species, with
               # all the mass values listed recorded for that sp
               pivot_wider(names_from=traitName, values_from=traitValue, values_fn=list), by=c('Species'='species')) %>%
  rowwise() %>%
  # sum Activities to see which lacks all values (==0)
  mutate(amb_act=sum(Noc, Diu, Crepu, na.rm=T)) %>%
  # only concerned with our focal taxa
  filter(Species %in% foc_taxa) %>%
  select(species, Body_mass_g, Mass, Activity, amb_act, Noc, Diu, Crepu, everything()) 
View(amphibioCOMP)
amphibioCOMP %>% ungroup() %>%
  mutate(a=case_when(is.na(Body_mass_g) & Mass=='NULL' ~'unknown',
                     !is.na(Body_mass_g) & Mass =='NULL' ~'amp',
                     is.na(Body_mass_g) & !is.na(Mass)~'atraiu',
                     T ~ 'both')) %>%
  filter(species %in% foc_taxa) %>% 
  group_by(a) %>% View()

amphibioCOMP %>% ungroup() %>%
  mutate(a=case_when(is.na(Body_mass_g) & Mass=='NULL' ~'unknown',
                     !is.na(Body_mass_g) & Mass =='NULL' ~'amp',
                     is.na(Body_mass_g) & !is.na(Mass)~'atraiu',
                     T ~ 'both')) %>%
  filter(species %in% foc_taxa) %>% 
  group_by(a) %>% tally()

amphibioCOMP %>% 
  filter(amb_act == 0) %>% 
  group_by(species) %>% slice(1) %>% nrow()

View(amphibio)
```

Other stats in discussion

```{r}
n_b4<-trait_long %>% left_join(refs, by='refID') %>%
  distinct(species, traitName, refID, .keep_all=T) %>%
  filter(year < 2008) %>% nrow()
n_all<-trait_long %>% left_join(refs, by='refID') %>%
  distinct(species, traitName, refID, .keep_all=T) %>%
  nrow()
n_b4/n_all
```

```{r}
trait_long %>%
  filter(traitName !='Mass',
         traitName !='Activity',
         lifeStage %in% c('adult','unknown')) %>%
  distinct(species, traitName, verbatimLocality) %>%
  count(traitName, species) %>%
  filter(n > 3) %>% arrange(desc(n))
trait_long %>% filter(traitName=='CTmax', species == 'Lithobates sylvaticus', lifeStage %in% c('adult','unknown'))
```


```{r}
trait_long %>%
  group_by(traitName) %>% 
  left_join(refs, by='refID') %>%
  filter(year==min(year)) %>%
  select(traitName, species, year, verbatimLocality)

```

